// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddLink(arg1:string,arg2:config.IConfigLinkGroup):Promise<void>;

export function AddServer(arg1:config.IConfigGroup):Promise<void>;

export function DeleteLink(arg1:string,arg2:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function ForceReload():Promise<void>;

export function GetActiveTunnelIds():Promise<Array<string>>;

export function GetConfig():Promise<config.IConfig>;

export function Greet(arg1:string):Promise<string>;

export function ModifyLink(arg1:string,arg2:string,arg3:config.IConfigLinkGroup):Promise<void>;

export function ModifyServer(arg1:string,arg2:config.IConfigGroup):Promise<void>;

export function ModifyServers(arg1:string,arg2:boolean):Promise<void>;

export function SetLanguage(arg1:boolean):Promise<void>;

export function ThemeSwitch(arg1:boolean):Promise<void>;

export function ToggleLinkStatus(arg1:string,arg2:string,arg3:boolean):Promise<void>;
