// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLink(arg1, arg2) {
  return window['go']['main']['App']['AddLink'](arg1, arg2);
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function DeleteLink(arg1, arg2) {
  return window['go']['main']['App']['DeleteLink'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function ForceReload() {
  return window['go']['main']['App']['ForceReload']();
}

export function GetActiveTunnelIds() {
  return window['go']['main']['App']['GetActiveTunnelIds']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ModifyLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModifyLink'](arg1, arg2, arg3);
}

export function ModifyServer(arg1, arg2) {
  return window['go']['main']['App']['ModifyServer'](arg1, arg2);
}

export function ModifyServers(arg1, arg2) {
  return window['go']['main']['App']['ModifyServers'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ThemeSwitch(arg1) {
  return window['go']['main']['App']['ThemeSwitch'](arg1);
}

export function ToggleLinkStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleLinkStatus'](arg1, arg2, arg3);
}
